site_name: MkDocs Material i18n

theme:
  name: material

plugins:
  - search
  - i18n:
      locales:
        - name: 中文
          link: /zh/
          lang: zh
          site_name: MkDocs Material 国际化插件
          nav:
            - 首页: index.md
            - 指南: guide.md
            - 文档: docs.md
        - name: English
          link: /en/
          lang: en
          site_name: MkDocs Material i18n Plugin
          nav:
            - Home: index.md
            - Guide: guide.md
            - API Reference: api.md